services:
  wise-slice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    develop:
      watch:
        - path: src
          action: rebuild
    environment:
      - NODE_ENV=production
    command: pnpm start
    # volumes:
    #   - .:/usr/src/app # mounts the current directory as /usr/src/app inside the container
    #   - /usr/src/app/node_modules # keeps node_modules cached between builds
